/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiculosRouteImport } from './routes/vehiculos'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as PropietariosRouteImport } from './routes/propietarios'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as CatalogosRouteImport } from './routes/catalogos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TarjetasIndexRouteImport } from './routes/tarjetas.index'
import { Route as TarjetasNuevaRouteImport } from './routes/tarjetas.nueva'
import { Route as TarjetasIdRouteImport } from './routes/tarjetas.$id'

const VehiculosRoute = VehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const PropietariosRoute = PropietariosRouteImport.update({
  id: '/propietarios',
  path: '/propietarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogosRoute = CatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarjetasIndexRoute = TarjetasIndexRouteImport.update({
  id: '/tarjetas/',
  path: '/tarjetas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarjetasNuevaRoute = TarjetasNuevaRouteImport.update({
  id: '/tarjetas/nueva',
  path: '/tarjetas/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const TarjetasIdRoute = TarjetasIdRouteImport.update({
  id: '/tarjetas/$id',
  path: '/tarjetas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogos': typeof CatalogosRoute
  '/consulta': typeof ConsultaRoute
  '/propietarios': typeof PropietariosRoute
  '/sql': typeof SqlRoute
  '/vehiculos': typeof VehiculosRoute
  '/tarjetas/$id': typeof TarjetasIdRoute
  '/tarjetas/nueva': typeof TarjetasNuevaRoute
  '/tarjetas/': typeof TarjetasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogos': typeof CatalogosRoute
  '/consulta': typeof ConsultaRoute
  '/propietarios': typeof PropietariosRoute
  '/sql': typeof SqlRoute
  '/vehiculos': typeof VehiculosRoute
  '/tarjetas/$id': typeof TarjetasIdRoute
  '/tarjetas/nueva': typeof TarjetasNuevaRoute
  '/tarjetas': typeof TarjetasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogos': typeof CatalogosRoute
  '/consulta': typeof ConsultaRoute
  '/propietarios': typeof PropietariosRoute
  '/sql': typeof SqlRoute
  '/vehiculos': typeof VehiculosRoute
  '/tarjetas/$id': typeof TarjetasIdRoute
  '/tarjetas/nueva': typeof TarjetasNuevaRoute
  '/tarjetas/': typeof TarjetasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogos'
    | '/consulta'
    | '/propietarios'
    | '/sql'
    | '/vehiculos'
    | '/tarjetas/$id'
    | '/tarjetas/nueva'
    | '/tarjetas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogos'
    | '/consulta'
    | '/propietarios'
    | '/sql'
    | '/vehiculos'
    | '/tarjetas/$id'
    | '/tarjetas/nueva'
    | '/tarjetas'
  id:
    | '__root__'
    | '/'
    | '/catalogos'
    | '/consulta'
    | '/propietarios'
    | '/sql'
    | '/vehiculos'
    | '/tarjetas/$id'
    | '/tarjetas/nueva'
    | '/tarjetas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogosRoute: typeof CatalogosRoute
  ConsultaRoute: typeof ConsultaRoute
  PropietariosRoute: typeof PropietariosRoute
  SqlRoute: typeof SqlRoute
  VehiculosRoute: typeof VehiculosRoute
  TarjetasIdRoute: typeof TarjetasIdRoute
  TarjetasNuevaRoute: typeof TarjetasNuevaRoute
  TarjetasIndexRoute: typeof TarjetasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehiculos': {
      id: '/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof VehiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propietarios': {
      id: '/propietarios'
      path: '/propietarios'
      fullPath: '/propietarios'
      preLoaderRoute: typeof PropietariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogos': {
      id: '/catalogos'
      path: '/catalogos'
      fullPath: '/catalogos'
      preLoaderRoute: typeof CatalogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarjetas/': {
      id: '/tarjetas/'
      path: '/tarjetas'
      fullPath: '/tarjetas/'
      preLoaderRoute: typeof TarjetasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarjetas/nueva': {
      id: '/tarjetas/nueva'
      path: '/tarjetas/nueva'
      fullPath: '/tarjetas/nueva'
      preLoaderRoute: typeof TarjetasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarjetas/$id': {
      id: '/tarjetas/$id'
      path: '/tarjetas/$id'
      fullPath: '/tarjetas/$id'
      preLoaderRoute: typeof TarjetasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogosRoute: CatalogosRoute,
  ConsultaRoute: ConsultaRoute,
  PropietariosRoute: PropietariosRoute,
  SqlRoute: SqlRoute,
  VehiculosRoute: VehiculosRoute,
  TarjetasIdRoute: TarjetasIdRoute,
  TarjetasNuevaRoute: TarjetasNuevaRoute,
  TarjetasIndexRoute: TarjetasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
